// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

const SUPABASE_URL = "https://qtgjgnxrnydubizzpvxa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF0Z2pnbnhybnlkdWJpenpwdnhhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc5OTYyMTIsImV4cCI6MjA2MzU3MjIxMn0.iST1fJnYMo4QFrlVxGDR5iMCIXYlZOreNUYmN8CQRC0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY,
);
